"""Build the comparison PDF (Gao et al. vs. our Module 1+2 dataset)."""
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
)

OUT = "Dataset_Comparison_Gao_vs_Ours.pdf"

styles = getSampleStyleSheet()
H1 = ParagraphStyle("H1", parent=styles["Heading1"], fontSize=16, spaceAfter=10)
H2 = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=13, spaceAfter=6)
H3 = ParagraphStyle("H3", parent=styles["Heading3"], fontSize=11, spaceAfter=4)
BODY = ParagraphStyle("BODY", parent=styles["BodyText"], fontSize=10, leading=14, spaceAfter=6)
ITEM = ParagraphStyle("ITEM", parent=BODY, leftIndent=14, bulletIndent=2)


def P(t):
    return Paragraph(t, BODY)


def B(t):
    return Paragraph(f"&bull; {t}", ITEM)


story = []

story.append(Paragraph(
    "Categories used by <i>Shaping the Safety Boundaries</i> (Gao et al., 2024)", H1))
story.append(P(
    "<b>Three prompt categories</b> (&sect;3.2 Experimental Settings):"))
story.append(B(
    "<b>Benign</b> &mdash; curated subset of <b>Alpaca</b> (Taori et al., 2023). "
    "Used because it is pre-filtered to contain only safe instructional content."))
story.append(B(
    "<b>Harmful</b> &mdash; direct harmful prompts pulled from <b>RedEval</b> "
    "(Bhardwaj &amp; Poria, 2023) plus <b>AdvBench</b> (Zou et al., 2023). "
    "Plain harmful requests an aligned model is expected to refuse."))
story.append(B(
    "<b>Jailbreak</b> &mdash; generated by running <b>seven</b> automated "
    "jailbreak attack methods on AdvBench prompts: GCG-Individual, "
    "GCG-Universal, AdvPrompter, COLD-Suffix, AutoDAN, PAIR, ArtPrompt."))
story.append(P(
    "<b>Total:</b> 32,507 samples. Activations are taken as the "
    "<b>last-token vector</b> of the input, projected via <b>MDS</b> "
    "(not PCA / t-SNE). Backbone: <b>Vicuna-7B-v1.3</b>, with extensions to "
    "Llama-2-7B-Chat, Qwen-1.5-0.5B-Chat, and Vicuna-13B-v1.5."))

story.append(Spacer(1, 0.15 * inch))
story.append(Paragraph(
    "Differences vs. the dataset we are building (Module 1 + Module 2)", H2))

table_data = [
    ["Axis", "Gao et al. - Safety Boundaries", "Ours - Module 1 + Module 2"],
    ["Category names",
     "benign / harmful / jailbreak",
     "benign / harmful_direct / jailbreak_wrapped"],
    ["Benign source",
     "Alpaca (instruction-following data)",
     "WikiText-103 (raw encyclopedic text)"],
    ["Harmful source",
     "RedEval + AdvBench only",
     "AdvBench + HarmBench + JailbreakBench + SaladBench"],
    ["Jailbreak source",
     "7 automated optimizers (GCG, AutoDAN, PAIR, AdvPrompter, COLD-Suffix, "
     "ArtPrompt, GCG-Universal) on AdvBench",
     "TrustAIRLab human-authored in-the-wild templates, filled with our "
     "harmful-request pool"],
    ["Label",
     "Category tag - prompt-type, not behavior verified",
     "Behavior-grounded - GPT-4 judge with tau=7 rubric on Gemma's actual "
     "response; label 1 only if substantively harmful"],
    ["Judge",
     "None for labeling. GPT-4o-mini used only for Just-Eval utility scoring",
     "GPT-4 (Azure or OpenAI) 3-step decision tree producing binary jailbreak "
     "label"],
    ["Activation pooled",
     "Last token of the input",
     "Mean of last 5 prompt tokens"],
    ["Layers studied",
     "All layers 0-31, focus on 4 / 15 / 30",
     "Fixed set {5, 10, 15, 20, 25} of Gemma's 26-block stack"],
    ["Projection / analysis",
     "MDS (preserves global geometry)",
     "PCA -> K-means -> DBSCAN -> UMAP"],
    ["Backbone model",
     "Vicuna-7B-v1.3, Llama-2-7B-Chat, Qwen-1.5-0.5B, Vicuna-13B",
     "Gemma-2-2b-it (single model)"],
    ["Dataset size",
     "32,507 samples total",
     "~11k prompts (4k benign + 2k harmful_direct + 5k jailbreak_wrapped)"],
    ["Goal of dataset",
     "Visualize safety boundary + train ABD inference-time defense that "
     "penalizes outlier activations",
     "Train CVAE generator + reward model + clustering detector to map the "
     "jailbreak subspace from benign-only corruption"],
]

cell_style = ParagraphStyle("cell", parent=BODY, fontSize=8.5, leading=11)
table = [[Paragraph(c, cell_style) for c in row] for row in table_data]
t = Table(table, colWidths=[1.3 * inch, 2.7 * inch, 2.7 * inch], repeatRows=1)
t.setStyle(TableStyle([
    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#222")),
    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ("TOPPADDING", (0, 0), (-1, -1), 5),
    ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
    ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ("ROWBACKGROUNDS", (0, 1), (-1, -1),
     [colors.whitesmoke, colors.HexColor("#f0f0f5")]),
]))
story.append(t)

story.append(PageBreak())
story.append(Paragraph("Conceptual differences", H2))

story.append(Paragraph("1. What \"jailbreak\" means in the data", H3))
story.append(P(
    "Gao et al. use <i>machine-optimized adversarial suffixes</i> &mdash; "
    "outputs of GCG/AutoDAN/PAIR &mdash; which produce specific, often "
    "non-semantic token strings. Our <code>jailbreak_wrapped</code> uses "
    "<i>human-crafted social-engineering wrappers</i> from TrustAIRLab "
    "(DAN-style personas, hypothetical framings). The activation geometry "
    "these two families induce is genuinely different: optimizer attacks "
    "push activations along narrow gradient directions, while wrapped "
    "attacks shift them through semantic role-play."))

story.append(Paragraph("2. Label semantics", H3))
story.append(P(
    "In Gao et al. a sample is &lsquo;jailbreak&rsquo; because it <i>came "
    "from</i> a jailbreak attack pipeline &mdash; the model&rsquo;s response "
    "is never inspected for the label. In our pipeline a sample is label-1 "
    "only if the GPT-4 judge confirms the response is substantively harmful. "
    "Our positive class is strictly smaller and behavior-verified, which "
    "matches our paper&rsquo;s &sect;3.6 verifier (tau=7) and is needed to "
    "train the reward model R_phi that predicts whether a perturbation "
    "delta_f actually induces jailbreak behavior."))

story.append(Paragraph("3. Benign distribution", H3))
story.append(P(
    "Alpaca instructions are short, instruction-formatted, and topically "
    "diverse &mdash; close to the distribution of the harmful and jailbreak "
    "prompts (also instructions). WikiText is <i>out-of-distribution</i> for "
    "instruction-following: long encyclopedic prose with no request "
    "structure. The choice is deliberate in our paper: &sect;3.3 uses "
    "WikiText specifically so the corruption pipeline operates on benign "
    "passages whose activations lie in a <i>non-instructional</i> region, "
    "and any jailbreak behavior elicited by delta_f injection is "
    "attributable to the perturbation, not to a residual harmful intent in "
    "the benign prompt."))

story.append(Paragraph("4. End goal of the dataset", H3))
story.append(P(
    "Gao et al. need labeled clusters to (a) visualize the safety boundary "
    "on MDS plots and (b) tune an inference-time penalty (ABD) via Bayesian "
    "optimization. We need labeled (benign, harmful) activation pairs to "
    "(a) warm-start the CVAE on a binary concept label, (b) train the "
    "reward model that scores whether a generated delta_f jailbreaks Gemma, "
    "and (c) build a prompt-agnostic detector from cluster centroids."))

story.append(Paragraph("5. Coverage of jailbreak diversity", H3))
story.append(P(
    "Theirs spans 7 <i>attack algorithms</i> on a single seed prompt set "
    "(AdvBench). Ours spans ~1.4k unique TrustAIRLab templates &times; "
    "multiple harmful payloads, capped at 20 fills/template &mdash; trading "
    "attack-algorithm diversity for template diversity within a single "
    "attack family (in-the-wild human wrappers)."))

story.append(Spacer(1, 0.15 * inch))
story.append(Paragraph("Bottom line", H2))
story.append(P(
    "Gao et al.&rsquo;s dataset is <b>algorithm-attack-centric</b> "
    "(optimizer outputs labeled by source) and <b>instruction-distribution "
    "benign</b>. Ours is <b>template-attack-centric</b> (human-authored "
    "wrappers labeled by behavior) and <b>non-instructional benign</b>. Both "
    "produce three categories, but the categories cover different slices of "
    "the jailbreak space and serve different downstream objectives &mdash; "
    "their categories drive a defense that lives at inference time, ours "
    "drive a generative/clustering map of the latent jailbreak subspace."))

doc = SimpleDocTemplate(
    OUT, pagesize=LETTER,
    leftMargin=0.7 * inch, rightMargin=0.7 * inch,
    topMargin=0.7 * inch, bottomMargin=0.7 * inch,
)
doc.build(story)
print(f"wrote {OUT}")
